### PR TITLE
Create non-cached tag map on thread-preview.

### PR DESCRIPTION
**Pull request by Xon**
Sets up a tag-map for previewing new posts or new threads.

Solves #10 

Testing to confirm this works as expected.

### CODE REVIEW

**Comment by Xon** [comment]
@cclaerhout do you have any feedback on this?

**Comment by cclaerhout** [comment]
It's 5am, I haven't slept yet ; I've reinstalled all my laptop os, softwares & personnal files ; I will look at it during this week.

**Comment by cclaerhout** [comment]
Should the Bb Code be cached if the visitor is not a member?

**Comment by Xon** [comment]
No rush!

We don't want to cache anything, as that this code-path is triggered when a user previews a new post. The post content may change quite significantly before it is saved and gets an actual post_id.

This allows bbcode parser permissions to work as expected when making new posts.

**Comment by cclaerhout** [comment]
Oops there's still this commit. My question: shouldn't your code be wrapped inside a conditional that checks if the visitor is not a guest? If you're sure of you, let's merge the pull request.

**Comment by Xon** [comment]
Oh, now I understand.

This code is only executed when a user is posting. If they are posting as a guest, the difference before this code existed is there is now a tag map generated for the post.

It doesn't really offer much, but consistently generating the tag map would be nice.

**Comment by cclaerhout** [comment]
Ok perfect thanks

**Pull request merged**
